name: My workflow

on:
  push:
    branches: 
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Secret
        run: echo "My API Key is ${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        
